# Site settings

title: My Cyber Universe
tagline: Back to the future!
description: At My Cyber Universe we specialize in web design, software and web development, but youâ€™ll also see us contributing tutorials, news and opinion pieces from time to time. Main goal is to be the source for anyone who wants to learn the web design, software and web development.

# the base hostname & protocol for your site
url: "http://mycyberuniverse.com"

# the subpath of your site, e.g. /blog
baseurl: ""


#markdown: kramdown
#kramdown:
#    input: GFM
#    syntax_highlighter: rouge
#    syntax_highlighter_opts:
#        disable: true
highlighter: rouge


index:
    en: index.html
    ru: _pages/ru/index.html
archive:
    en: _pages/en/archive.html
    ru: _pages/ru/archive.html
author:
    en: _pages/en/author.html
    ru: _pages/ru/author.html
contact:
    en: _pages/en/contact.html
    ru: _pages/ru/contact.html
contact-thanks:
    en: _pages/en/contact-thanks.html
    ru: _pages/ru/contact-thanks.html
donate:
    en: _pages/en/donate.html
    ru: _pages/ru/donate.html
feed:
    en: feed.xml
    ru: feed.xml

email: arthurgareginyan@gmail.com
twitter_username: AGareginyan
github_username:  ArthurGareginyan

include: ['_pages']
exclude: [vendor]

gems:
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
