##### WEBSITE SETTINGS #####


##### Website Title, Tagline and Description
title: My Cyber Universe
tagline: Back to the future!
description: At My Cyber Universe we specialize in web design, software and web development, but youâ€™ll also see us contributing tutorials, news and opinion pieces from time to time. Main goal is to be the source for anyone who wants to learn the web design, software and web development.



##### The base hostname & protocol for the website
url: "http://mycyberuniverse.com"

##### The subpath of the website, e.g. /blog
baseurl: ""



##### Syntax Highlighter
highlighter: rouge



##### Pages (in EN and RU languages)
index:
    en: index.html
    ru: _pages/ru/index.html
archive:
    en: _pages/en/archive.html
    ru: _pages/ru/archive.html
about:
    en: _pages/en/about.html
    ru: _pages/ru/about.html
contact:
    en: _pages/en/contact.html
    ru: _pages/ru/contact.html
contact-thanks:
    en: _pages/en/contact-thanks.html
    ru: _pages/ru/contact-thanks.html
donate:
    en: _pages/en/donate.html
    ru: _pages/ru/donate.html
feed:
    en: feed.xml
    ru: feed.xml



##### Data for the jekyll-seo-tag plugin
logo: /images/MCU-logo.png
twitter:
    username: AGareginyan
facebook:
    app_id:
    publisher:
    admins:
social:
    name: Arthur Gareginyan
    links:
        - https://www.facebook.com/arthur.gareginyan
        - https://twitter.com/AGareginyan
        - https://www.instagram.com/arthur_gareginyan/
        - https://www.linkedin.com/in/arthurgareginyan
        - https://github.com/ArthurGareginyan
        - https://profiles.wordpress.org/arthur-gareginyan/
        - https://www.behance.net/ArthurGareginyan



##### Author details
authors:
    Arthur Gareginyan:
        name: Arthur
        full_name: Arthur Gareginyan
        photo: /images/avatar/arthur.jpg
        email: arthurgareginyan@gmail.com
        web: //www.arthurgareginyan.com
        bio: Arthur is a designer and full stack software engineer. He is the founder of MyCyberUniverse.com. His personal website can be found at <a href="//www.arthurgareginyan.com">arthurgareginyan.com</a>. Check out his free WordPress plugins at <a href="https://profiles.wordpress.org/arthur-gareginyan/">wordpress.org</a>.
    Milena Kiseleva:
        name: Milena
        full_name: Milena Kiseleva
        photo: /images/avatar/milena.jpg
        email: milavakiseleva@gmail.com
        web: //milenakiseleva.github.io
        bio: Milena is a web designer and illustrator. She spends her time translating our articles and wrote her own articles. Her personal website can be found at <a href="//milenakiseleva.github.io">milenakiseleva.github.io</a>.



email: arthurgareginyan@gmail.com



include: ['_pages']
exclude: [vendor]



##### Enabled plugins
gems:
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
