##### WEBSITE SETTINGS #####


##### Website Title, Tagline and Description
title: My Cyber Universe
tagline: Back to the future!
description: At My Cyber Universe we specialize in web design, software and web development, but youâ€™ll also see us contributing tutorials, news and opinion pieces from time to time. Main goal is to be the source for anyone who wants to learn the web design, software and web development.



##### The base hostname & protocol for the website
url: "http://mycyberuniverse.com"

##### The subpath of the website, e.g. /blog
baseurl: ""



##### Syntax Highlighter
highlighter: rouge



##### Pages (in EN and RU languages)
index:
    en: index.html
    ru: _pages/ru/index.html
archive:
    en: _pages/en/archive.html
    ru: _pages/ru/archive.html
author:
    en: _pages/en/author.html
    ru: _pages/ru/author.html
contact:
    en: _pages/en/contact.html
    ru: _pages/ru/contact.html
contact-thanks:
    en: _pages/en/contact-thanks.html
    ru: _pages/ru/contact-thanks.html
donate:
    en: _pages/en/donate.html
    ru: _pages/ru/donate.html
feed:
    en: feed.xml
    ru: feed.xml



##### Data for the jekyll-seo-tag plugin
logo: /images/MCU-logo.png
twitter:
    username: AGareginyan
social:
    name: Arthur Gareginyan
    links:
        - https://www.facebook.com/arthur.gareginyan
        - https://twitter.com/AGareginyan
        - https://www.instagram.com/arthur_gareginyan/
        - https://www.linkedin.com/in/arthurgareginyan
        - https://github.com/ArthurGareginyan
        - https://profiles.wordpress.org/arthur-gareginyan/
        - https://www.behance.net/ArthurGareginyan

email: arthurgareginyan@gmail.com



include: ['_pages']
exclude: [vendor]

gems:
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
